name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # Job name is Test
    name: Build
    # This job runs on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform:iOS Simulator, id:C9A792D9-3C59-49B2-840E-F51E6BD9BF5C, OS:13.3, name:iPhone 8']
        xcode: ['/Applications/Xcode.app/Contents/Developer']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.3.app/Contents/Developer
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Install Dependences
      run: |
        pod repo update
        pod install
      shell: bash
          
    - name: Build and test
      run: |
        xcodebuild clean test \
        -workspace EasyMeals.xcworkspace \
        -scheme EasyMeals \
        -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
